@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor usuario
usuario -> JuegoPantallaPpalControllers: iniciar partida
activate JuegoPantallaPpalControllers
JuegoPantallaPpalControllers->ParamatrosControllers: seleccionar parametros
activate ParamatrosControllers
ParamatrosControllers->TableroControllers: cargar datos partida
activate TableroControllers
TableroControllers-->usuario: muestra datos
usuario->TableroControllers:Finalizar partida
TableroControllers->GuardarControllers: se guarda la información


@enduml